sqlLite:
  enable: true
  file: "database.sql"
mysql:
  enable: false
  host:
  bdd:
  username:
  password:
  tablePrefix:
config:
  currencyName: "EURO"
  currencySign: "€"
messages:
  prefix: "[MONEY]"
  accountCantCreate: "&cVotre compte n'a pas pu être créé"
  noPermission: "&cVous n'avez pas la permission."
  noPossible: "&cVous ne pouvez pas faire cela."
  consoleOnly: "&cSeul la console peut faire cela."
  internalError: "&cUn incident a eu lieu, veuillez contacter un administrateur !"
  soldePlayer: "Le solde de votre compte est de {money} {currencyName}"
  soldeOtherPlayer: "Le solde du compte de {playerName} est de {money} {currencyName}"
  playerNoAccount: "Ce joueur n'a pas de compte !"
  playerHasAccount: "Ce joueur a déjà un compte !"
  playerIsNotOnline: "Ce joueur n'est pas connecté !"
  playerInsufficientBalance: "Ce joueur n'a pas assez d'argent !"
  amountIsNotANumber: "Le montant doit être un nombre !"
  amountIncorrect: "Le montant doit être supérieur à 0 !"
  insufficientBalance: "Vous n'avez pas assez d'argent !"
  commandPayUsage: "/pay <joueur> <montant>"
  payCommandUsage: "/money pay <joueur> <montant>"
  paymentSentTo: "Vous avez envoyé {money} {currencyName} à {targetName}"
  paymentReceivedFrom: "Vous avez reçu {money} {currencyName} de {fromName}"
  giveCommandUsage: "/money give <joueur> <montant>"
  youReceived: "Vous avez reçu {money} {currencyName}"
  youGiveTo: "Vous avez donné {money} {currencyName} à {targetName} "
  takeCommandUsage: "/money take <joueur> <montant>"
  youLost: "Vous avez perdu {money} {currencyName}"
  youTakeTo: "Vous avez pris {money} {currencyName} à {targetName} "
  createCommandUsage: "/money create <joueur> "
  createAccountTo: "Vous avez crée le compte de {targetName}"
  setCommandUsage: "/money set <joueur> <montant>"
  youSet: "Le solde de votre compte a été définir à {money} {currencyName}"
  youSetTo: "Vous avez défini le solde du compte de {targetName} à {money} {currencyName}"
  deleteCommandUsage: "/money delete <joueur>"
  deleteAccountImpossible: "Le joueur est connecté, impossible de supprimer le compte !"
  youDeleteAccountTo: "Vous avez supprimé le compte de {targetName}"
  resetAccountTo: "Vous avez reset le compte de {targetName}"
  totalAccountReset: "Vous avez reset {number} compte(s) ( {error} Erreur(s) survenue(s) )"
  totalAccountDelete: "Vous avez supprimé {number} compte(s) ( {error} Erreur(s) survenue(s) )"
  kickPlayerDelete: "Votre compte a été supprimé"
  helpCommand:
    header: "&8&m-----------------------------------------------------"
    balanceHelp: "&a/money balance &8» &7Permet de connaître le solde de votre compte"
    balanceOtherHelp: "&a/money balance <joueur> &8» &7Permet de connaître le solde d'un autre compte"
    payHelp: "&a/money pay <joueur> <montant> &8» &7Payer un joueur"
    giveHelp: "&a/money give <joueur> <montant> &8» &7Donner de l'argent à un joueur"
    takeHelp: "&a/money take <joueur> <montant> &8» &7Retirer de l'argent à un joueur"
    setHelp: "&a/money set <joueur> <montant> &8» &7Définir le solde d'un joueur"
    createHelp: "&a/money create <joueur> &8» &7Créer le compte d'un joueur manuellement"
    deleteHelp: "&a/money delete <joueur> &8» &7Supprimer le compte d'un joueur"
    resetAllHelp: "&a/money resetall &8» &7Reset TOUS les comptes"
    deleteAllHelp: "&a/money deleteall &8» &7Supprimer TOUS les comptes"
    footer: "&8&m-----------------------------------------------------"
