sqlLite:
  enable: true
  file: "database.sql"
mysql:
  enable: false
  host:
  bdd:
  username:
  password:
  tablePrefix:
config:
  currencyName: "EURO"
  currencySign: "€"
messages:
  prefix: "[MONEY]"
  accountCantCreate: "&cVotre compte n'a pas pu être créé"
  noPermission: "&cVous n'avez pas la permission."
  noPossible: "&cVous ne pouvez pas faire cela."
  internalError: "&cUn incident a eu lieu, veuillez contacter un administrateur !"
  soldePlayer: "Le solde de votre compte est de {money} {currencyName}"
  soldeOtherPlayer: "Le solde du compte de {playerName} est de {money} {currencyName}"
  playerNoAccount: "Ce joueur n'a pas de compte !"
  playerHasAccount: "Ce joueur a déjà un compte !"
  playerIsNotOnline: "Ce joueur n'est pas connecté !"
  playerInsufficientBalance: "Ce joueur n'a pas assez d'argent !"
  amountIsNotANumber: "Le montant doit être un nombre !"
  amountIncorrect: "Le montant doit être supérieur à 0 !"
  insufficientBalance: "Vous n'avez pas assez d'argent !"
  payCommandUsage: "/money pay <joueur> <montant>"
  paymentSentTo: "Vous avez envoyé {money} {currencyName} à {targetName}"
  paymentReceivedFrom: "Vous avez reçu {money} {currencyName} de {fromName}"
  giveCommandUsage: "/money give <joueur> <montant>"
  youReceived: "Vous avez reçu {money} {currencyName}"
  youGiveTo: "Vous avez donné {money} {currencyName} à {targetName} "
  takeCommandUsage: "/money take <joueur> <montant>"
  youLost: "Vous avez perdu {money} {currencyName}"
  youTakeTo: "Vous avez pris {money} {currencyName} à {targetName} "
  createCommandUsage: "/money take <joueur> <montant>"
  createAccountTo: "Vous avez crée le compte de {targetName}"
  setCommandUsage: "/money set <joueur> <montant>"
  youSet: "Le solde de votre compte a été définir à {money} {currencyName}"
  youSetTo: "Vous avez défini le solde du compte de {targetName} à {money} {currencyName} "