sqlLite:
  enable: true
  file: "database.sql"
mysql:
  enable: false
  host:
  bdd:
  username:
  password:
  tablePrefix:
config:
  currencyName: "EURO"
  currencySign: "€"
messages:
  prefix: "[MONEY]"
  accountCantCreate: "Votre compte n'a pas pu être créé"